services:
  digital-signage:
    image: digital_signage_introduction-digital-signage
    container_name: digital-signage-app
    ports:
      - "65002:65002"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - HTTP_PROXY=
      - http_proxy=
      - HTTPS_PROXY=
      - https_proxy=
      - NO_PROXY=
      - no_proxy=
